title: JaviReqs
email: 
description: "Javier Hernandez Requena Web Portfolio."
twitter_username: javireqs
github_username: javireqs
minimal_mistakes_skin: neon  # Using the neon skin, adjust to your preference
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 10  # Show 10 posts per page
timezone: # You can set your timezone here

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author information
author:
  name: "Javier Hernandez Requena"
  avatar: "/assets/images/bio-photo.jpg"  # Ensure this image exists
  bio: "What's up! Welcome to my page, hope you enjoy it."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/javireqs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javireqs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/javireqs"

# Footer links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/javireqs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javireqs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/javireqs"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
