# Site settings
title: JaviReqs Portfolio
email: your-email@example.com
description: >-
  Javier Hernandez Requena is a cybersecurity researcher and technology enthusiast. 
  Explore my projects, blog posts, and contact me for collaborations.
twitter_username: javireqs
github_username: javireqs
minimal_mistakes_skin: neon  # Choose a skin for the theme
search: true

# Remote theme
remote_theme: "mmistakes/minimal-mistakes"  # Use the Minimal Mistakes theme from GitHub

# Base URL
url: "https://javireqs.github.io"
baseurl: ""  # Leave empty for GitHub Pages

# Permalinks and pagination
permalink: /:categories/:title/
paginate: 10

# Include
include:
  - _pages

# Timezone
timezone: America/Los_Angeles

# Social Links
author:
  name: "Javier Hernandez Requena"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Cybersecurity researcher and technology enthusiast."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/javireqs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javireqs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/javireqs"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/javireqs"
# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/


# Footer customization
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/javireqs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javireqs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/javireqs"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/javireqs"
  about:
    content: "Javier Hernandez Requena is a cybersecurity researcher and developer specializing in hardware and autonomous vehicles."
  copyright: "© 2024 JaviReqs. All Rights Reserved."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# SEO and Analytics
google_analytics: UA-XXXXXXXX-X  # Replace with your Google Analytics tracking ID
